option('sass_include_path', type : 'string', value : '', description : 'Optional load path given to sass')
option('install', type : 'boolean', value : false, description : 'Install the theme')
option('offline', type : 'boolean', value : false, description : 'Avoid online operations like npm install')